### ISSUE TITLE
How to observe all the time not just once?

### ISSUE THREAD

**Issue by tawgul** [freqdec/peekaboo#3]
Hi.

Did you think of adding such an option?

**Comment by freqdec** [comment]
Hi Tom,

I'm afraid not as it would involve a pretty much complete polyfill of the IntersectionObserver in order to run in IE10 and some older Android browsers etc. I want to keep the script small and on-point.

If you really need this then I suggest just using the IntersectionObserver API and, if really necessary, loading a polyfill for non-compliant browsers after a feature test fails.

Regards,
Brian
